export type CatalogProduct = {
  id: string;
  category: string;
  name: string;
  specs: string;
  price: number;
  from: boolean;
  options: string;
  image: string;
  details: string;
  badge: string;
};

export const catalogCategories = [
  "Todos",
  "Drones",
  "Garmin",
  "Áudio",
  "Acessórios",
  "Apple Watch",
  "iPad",
  "Mac",
  "Xiaomi",
  "iPhones seminovos",
  "iPhones lacrados"
] as const;

export const catalogProducts: CatalogProduct[] = [
  {
    "id": "dji-neo-combo-controle-3-baterias-1",
    "category": "Drones",
    "name": "DJI Neo Combo",
    "specs": "Controle + 3 baterias",
    "price": 2676,
    "from": false,
    "options": "Combo completo",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-neo-motion-combo-controle-3-baterias-2",
    "category": "Drones",
    "name": "DJI Neo Motion Combo",
    "specs": "Controle + 3 baterias",
    "price": 3888,
    "from": false,
    "options": "Motion Combo",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-neo-2-somente-drone-1-bateria-3",
    "category": "Drones",
    "name": "DJI Neo 2",
    "specs": "Somente drone + 1 bateria",
    "price": 1818,
    "from": false,
    "options": "1 bateria",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-neo-2-combo-controle-3-baterias-4",
    "category": "Drones",
    "name": "DJI Neo 2 Combo",
    "specs": "Controle + 3 baterias",
    "price": 3181,
    "from": false,
    "options": "Combo",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-neo-2-motion-combo-controle-3-baterias-5",
    "category": "Drones",
    "name": "DJI Neo 2 Motion Combo",
    "specs": "Controle + 3 baterias",
    "price": 4393,
    "from": false,
    "options": "Motion Combo",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-lito-1-controle-1-bateria-6",
    "category": "Drones",
    "name": "DJI Lito 1",
    "specs": "Controle + 1 bateria",
    "price": 2777,
    "from": false,
    "options": "1 bateria",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-lito-1-combo-controle-3-baterias-7",
    "category": "Drones",
    "name": "DJI Lito 1 Combo",
    "specs": "Controle + 3 baterias",
    "price": 3888,
    "from": false,
    "options": "Combo",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-lito-x1-controle-1-bateria-8",
    "category": "Drones",
    "name": "DJI Lito X1",
    "specs": "Controle + 1 bateria",
    "price": 3181,
    "from": false,
    "options": "1 bateria",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-lito-x1-combo-controle-3-baterias-9",
    "category": "Drones",
    "name": "DJI Lito X1 Combo",
    "specs": "Controle + 3 baterias",
    "price": 4494,
    "from": false,
    "options": "Combo",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-felipe-controle-com-tela-1-bateria-10",
    "category": "Drones",
    "name": "DJI Felipe",
    "specs": "Controle com tela + 1 bateria",
    "price": 3686,
    "from": false,
    "options": "1 bateria",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-felipe-combo-controle-com-tela-3-baterias-11",
    "category": "Drones",
    "name": "DJI Felipe Combo",
    "specs": "Controle com tela + 3 baterias",
    "price": 4393,
    "from": false,
    "options": "Combo",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-mini-5-pro-controle-1-bateria-12",
    "category": "Drones",
    "name": "DJI Mini 5 Pro",
    "specs": "Controle + 1 bateria",
    "price": 5504,
    "from": false,
    "options": "1 bateria",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-mini-5-pro-combo-controle-3-baterias-13",
    "category": "Drones",
    "name": "DJI Mini 5 Pro Combo",
    "specs": "Controle + 3 baterias",
    "price": 6817,
    "from": false,
    "options": "Combo",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-mini-5-pro-combo-plus-rc2-com-tela-3-baterias-de-36-min-14",
    "category": "Drones",
    "name": "DJI Mini 5 Pro Combo Plus",
    "specs": "RC2 com tela + 3 baterias de 36 min",
    "price": 8080,
    "from": false,
    "options": "36 minutos",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "dji-mini-5-pro-combo-plus-rc2-com-tela-3-baterias-de-52-min-15",
    "category": "Drones",
    "name": "DJI Mini 5 Pro Combo Plus",
    "specs": "RC2 com tela + 3 baterias de 52 min",
    "price": 8736,
    "from": false,
    "options": "52 minutos",
    "image": "./catalog/drone.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "antigravity-a1-explorer-bundle-8k-360-controle-com-oculos-3-baterias-16",
    "category": "Drones",
    "name": "AntiGravity A1 Explorer Bundle",
    "specs": "8K 360° · controle com óculos · 3 baterias",
    "price": 8433,
    "from": false,
    "options": "Explorer Bundle",
    "image": "./catalog/drone.webp",
    "details": "Captação imersiva em 360°",
    "badge": "8K"
  },
  {
    "id": "garmin-forerunner-70-relogio-esportivo-17",
    "category": "Garmin",
    "name": "Garmin Forerunner 70",
    "specs": "Relógio esportivo",
    "price": 1515,
    "from": false,
    "options": "Lilás · Verde",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-forerunner-165-gps-running-smartwatch-18",
    "category": "Garmin",
    "name": "Garmin Forerunner 165",
    "specs": "GPS running smartwatch",
    "price": 1363,
    "from": true,
    "options": "Preto · Branco",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-forerunner-170-relogio-esportivo-19",
    "category": "Garmin",
    "name": "Garmin Forerunner 170",
    "specs": "Relógio esportivo",
    "price": 1818,
    "from": false,
    "options": "Preto · Branco",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-forerunner-265-relogio-esportivo-20",
    "category": "Garmin",
    "name": "Garmin Forerunner 265",
    "specs": "Relógio esportivo",
    "price": 2373,
    "from": false,
    "options": "Branco",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-forerunner-570-42-mm-21",
    "category": "Garmin",
    "name": "Garmin Forerunner 570",
    "specs": "42 mm",
    "price": 2878,
    "from": false,
    "options": "Preto",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-forerunner-570-47-mm-22",
    "category": "Garmin",
    "name": "Garmin Forerunner 570",
    "specs": "47 mm",
    "price": 2979,
    "from": false,
    "options": "Preto · Roxo",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-venu-3s-smartwatch-23",
    "category": "Garmin",
    "name": "Garmin Venu 3S",
    "specs": "Smartwatch",
    "price": 2272,
    "from": false,
    "options": "Preto · Branco · Rosa",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-venu-3-smartwatch-24",
    "category": "Garmin",
    "name": "Garmin Venu 3",
    "specs": "Smartwatch",
    "price": 2474,
    "from": false,
    "options": "Preto · Branco",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-venu-4-41-mm-25",
    "category": "Garmin",
    "name": "Garmin Venu 4",
    "specs": "41 mm",
    "price": 3232,
    "from": false,
    "options": "Lilás · Preto",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-vivoactive-6-smartwatch-26",
    "category": "Garmin",
    "name": "Garmin vívoactive 6",
    "specs": "Smartwatch",
    "price": 1868,
    "from": false,
    "options": "Preto · Verde",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-fenix-8-51-mm-amoled-010-02905-00-27",
    "category": "Garmin",
    "name": "Garmin fēnix 8",
    "specs": "51 mm · AMOLED · 010-02905-00",
    "price": 5605,
    "from": false,
    "options": "Preto",
    "image": "./catalog/garmin.webp",
    "details": "Relógio multiesportivo premium",
    "badge": "AMOLED"
  },
  {
    "id": "garmin-edge-840-solar-ciclocomputador-gps-28",
    "category": "Garmin",
    "name": "Garmin Edge 840 Solar",
    "specs": "Ciclocomputador GPS",
    "price": 3080,
    "from": false,
    "options": "Solar",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-etrex-solar-gps-portatil-29",
    "category": "Garmin",
    "name": "Garmin eTrex Solar",
    "specs": "GPS portátil",
    "price": 1161,
    "from": false,
    "options": "Solar",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-gpsmap-66i-gps-portatil-com-comunicacao-30",
    "category": "Garmin",
    "name": "Garmin GPSMAP 66i",
    "specs": "GPS portátil com comunicação",
    "price": 2171,
    "from": false,
    "options": "Única",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "garmin-alpha-300-dispositivo-gps-31",
    "category": "Garmin",
    "name": "Garmin Alpha 300",
    "specs": "Dispositivo GPS",
    "price": 4444,
    "from": false,
    "options": "Única",
    "image": "./catalog/garmin.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "airpods-4-estojo-usb-c-32",
    "category": "Áudio",
    "name": "AirPods 4",
    "specs": "Estojo USB-C",
    "price": 848,
    "from": false,
    "options": "Regular",
    "image": "./catalog/airpods.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "airpods-4-anc-cancelamento-ativo-de-ruido-33",
    "category": "Áudio",
    "name": "AirPods 4 ANC",
    "specs": "Cancelamento ativo de ruído",
    "price": 1101,
    "from": false,
    "options": "Branco",
    "image": "./catalog/airpods.webp",
    "details": "Com ANC",
    "badge": "ANC"
  },
  {
    "id": "airpods-pro-3-usb-c-34",
    "category": "Áudio",
    "name": "AirPods Pro 3",
    "specs": "USB-C",
    "price": 1444,
    "from": false,
    "options": "Branco",
    "image": "./catalog/airpods.webp",
    "details": "Modelo Pro",
    "badge": ""
  },
  {
    "id": "airpods-5-estojo-padrao-35",
    "category": "Áudio",
    "name": "AirPods 5",
    "specs": "Estojo padrão",
    "price": 1182,
    "from": false,
    "options": "Branco",
    "image": "./catalog/airpods.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "airpods-5-wireless-estojo-com-recarga-sem-fio-36",
    "category": "Áudio",
    "name": "AirPods 5 Wireless",
    "specs": "Estojo com recarga sem fio",
    "price": 1283,
    "from": false,
    "options": "Branco",
    "image": "./catalog/airpods.webp",
    "details": "Recarga sem fio",
    "badge": ""
  },
  {
    "id": "airpods-max-usb-c-headphone-over-ear-37",
    "category": "Áudio",
    "name": "AirPods Max USB-C",
    "specs": "Headphone over-ear",
    "price": 2767,
    "from": false,
    "options": "Roxo",
    "image": "./catalog/airpods.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "airpods-max-usb-c-2-edicao-2026-38",
    "category": "Áudio",
    "name": "AirPods Max USB-C 2",
    "specs": "Edição 2026",
    "price": 2877,
    "from": true,
    "options": "Laranja · Roxo · Azul · Starlight · Midnight",
    "image": "./catalog/airpods.webp",
    "details": "Consulte a cor disponível",
    "badge": "2026"
  },
  {
    "id": "apple-pencil-usb-c-caneta-para-ipad-39",
    "category": "Acessórios",
    "name": "Apple Pencil USB-C",
    "specs": "Caneta para iPad",
    "price": 621,
    "from": false,
    "options": "Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "apple-pencil-pro-caneta-profissional-para-ipad-40",
    "category": "Acessórios",
    "name": "Apple Pencil Pro",
    "specs": "Caneta profissional para iPad",
    "price": 838,
    "from": false,
    "options": "Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "airtag-1-unidade-2-geracao-41",
    "category": "Acessórios",
    "name": "AirTag",
    "specs": "1 unidade · 2ª geração",
    "price": 333,
    "from": false,
    "options": "Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "airtag-4-unidades-1-geracao-42",
    "category": "Acessórios",
    "name": "AirTag",
    "specs": "4 unidades · 1ª geração",
    "price": 626,
    "from": false,
    "options": "Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "airtag-4-unidades-2-geracao-43",
    "category": "Acessórios",
    "name": "AirTag",
    "specs": "4 unidades · 2ª geração",
    "price": 737,
    "from": false,
    "options": "Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "magic-mouse-3-usb-c-mouse-apple-44",
    "category": "Acessórios",
    "name": "Magic Mouse 3 USB-C",
    "specs": "Mouse Apple",
    "price": 655,
    "from": true,
    "options": "Branco · Preto",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "magic-trackpad-trackpad-apple-45",
    "category": "Acessórios",
    "name": "Magic Trackpad",
    "specs": "Trackpad Apple",
    "price": 958,
    "from": false,
    "options": "Preto · Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "magic-keyboard-para-ipad-pro-m4-e-m5-11-polegadas-46",
    "category": "Acessórios",
    "name": "Magic Keyboard para iPad Pro",
    "specs": "M4 e M5 · 11 polegadas",
    "price": 2424,
    "from": false,
    "options": "Preto",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "magic-keyboard-para-ipad-air-m3-e-m4-13-polegadas-47",
    "category": "Acessórios",
    "name": "Magic Keyboard para iPad Air",
    "specs": "M3 e M4 · 13 polegadas",
    "price": 2525,
    "from": false,
    "options": "Preto · Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "cabo-usb-c-para-lightning-1-metro-original-48",
    "category": "Acessórios",
    "name": "Cabo USB-C para Lightning",
    "specs": "1 metro · original",
    "price": 131,
    "from": false,
    "options": "Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "cabo-usb-c-para-lightning-2-metros-original-49",
    "category": "Acessórios",
    "name": "Cabo USB-C para Lightning",
    "specs": "2 metros · original",
    "price": 192,
    "from": false,
    "options": "Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "cabo-usb-c-1-metro-original-50",
    "category": "Acessórios",
    "name": "Cabo USB-C",
    "specs": "1 metro · original",
    "price": 141,
    "from": false,
    "options": "Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "cabo-usb-c-2-metros-original-51",
    "category": "Acessórios",
    "name": "Cabo USB-C",
    "specs": "2 metros · original",
    "price": 202,
    "from": false,
    "options": "Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "fonte-usb-c-original-genuina-52",
    "category": "Acessórios",
    "name": "Fonte USB-C",
    "specs": "Original genuína",
    "price": 172,
    "from": false,
    "options": "Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "carregador-para-apple-watch-usb-c-similar-com-garantia-53",
    "category": "Acessórios",
    "name": "Carregador para Apple Watch",
    "specs": "USB-C · similar com garantia",
    "price": 172,
    "from": false,
    "options": "Branco",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "apple-watch-se-3-40-mm-gps-54",
    "category": "Apple Watch",
    "name": "Apple Watch SE 3",
    "specs": "40 mm · GPS",
    "price": 1636,
    "from": true,
    "options": "Midnight · Starlight",
    "image": "./catalog/watch.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "apple-watch-se-3-44-mm-gps-55",
    "category": "Apple Watch",
    "name": "Apple Watch SE 3",
    "specs": "44 mm · GPS",
    "price": 1766,
    "from": false,
    "options": "Starlight · Midnight",
    "image": "./catalog/watch.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "apple-watch-series-11-42-mm-gps-56",
    "category": "Apple Watch",
    "name": "Apple Watch Series 11",
    "specs": "42 mm · GPS",
    "price": 2151,
    "from": false,
    "options": "Rosa",
    "image": "./catalog/watch.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "apple-watch-series-11-46-mm-gps-57",
    "category": "Apple Watch",
    "name": "Apple Watch Series 11",
    "specs": "46 mm · GPS",
    "price": 2372,
    "from": false,
    "options": "Cinza · Rosa",
    "image": "./catalog/watch.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "apple-watch-series-12-42-mm-gps-58",
    "category": "Apple Watch",
    "name": "Apple Watch Series 12",
    "specs": "42 mm · GPS",
    "price": 2727,
    "from": false,
    "options": "Jet Black",
    "image": "./catalog/watch.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "apple-watch-series-12-46-mm-gps-59",
    "category": "Apple Watch",
    "name": "Apple Watch Series 12",
    "specs": "46 mm · GPS",
    "price": 3030,
    "from": false,
    "options": "Jet Black",
    "image": "./catalog/watch.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "apple-watch-ultra-4-gps-cellular-60",
    "category": "Apple Watch",
    "name": "Apple Watch Ultra 4",
    "specs": "GPS + Cellular",
    "price": 5099,
    "from": false,
    "options": "Preto",
    "image": "./catalog/watch.webp",
    "details": "Caixa Ultra",
    "badge": "Ultra"
  },
  {
    "id": "apple-watch-ultra-3-49-mm-ocean-band-61",
    "category": "Apple Watch",
    "name": "Apple Watch Ultra 3",
    "specs": "49 mm · Ocean Band",
    "price": 4494,
    "from": false,
    "options": "Caixa natural · pulseira azul",
    "image": "./catalog/watch.webp",
    "details": "Pulseira Ocean",
    "badge": "Ultra"
  },
  {
    "id": "apple-watch-ultra-3-49-mm-pulseira-milanesa-62",
    "category": "Apple Watch",
    "name": "Apple Watch Ultra 3",
    "specs": "49 mm · pulseira milanesa",
    "price": 5504,
    "from": false,
    "options": "Caixa natural",
    "image": "./catalog/watch.webp",
    "details": "Pulseira milanesa",
    "badge": "Ultra"
  },
  {
    "id": "ipad-a16-128-gb-wi-fi-63",
    "category": "iPad",
    "name": "iPad A16",
    "specs": "128 GB · Wi‑Fi",
    "price": 2858,
    "from": true,
    "options": "Azul · Rosa · Prateado",
    "image": "./catalog/ipad.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "ipad-a16-256-gb-wi-fi-64",
    "category": "iPad",
    "name": "iPad A16",
    "specs": "256 GB · Wi‑Fi",
    "price": 3484,
    "from": true,
    "options": "Prateado · Azul · Rosa",
    "image": "./catalog/ipad.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "ipad-mini-a17-128-gb-wi-fi-65",
    "category": "iPad",
    "name": "iPad mini A17",
    "specs": "128 GB · Wi‑Fi",
    "price": 4191,
    "from": false,
    "options": "Cinza-espacial · Starlight · Roxo · Azul",
    "image": "./catalog/ipad.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "ipad-air-m3-128-gb-11-polegadas-wi-fi-66",
    "category": "iPad",
    "name": "iPad Air M3",
    "specs": "128 GB · 11 polegadas · Wi‑Fi",
    "price": 3989,
    "from": false,
    "options": "Cinza-espacial · Azul",
    "image": "./catalog/ipad.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "ipad-air-m3-128-gb-13-polegadas-wi-fi-67",
    "category": "iPad",
    "name": "iPad Air M3",
    "specs": "128 GB · 13 polegadas · Wi‑Fi",
    "price": 4747,
    "from": false,
    "options": "Cinza-espacial",
    "image": "./catalog/ipad.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "ipad-air-m4-128-gb-11-polegadas-wi-fi-68",
    "category": "iPad",
    "name": "iPad Air M4",
    "specs": "128 GB · 11 polegadas · Wi‑Fi",
    "price": 4444,
    "from": true,
    "options": "Azul · Roxo · Cinza · Starlight",
    "image": "./catalog/ipad.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "ipad-air-m4-256-gb-11-polegadas-wi-fi-69",
    "category": "iPad",
    "name": "iPad Air M4",
    "specs": "256 GB · 11 polegadas · Wi‑Fi",
    "price": 5200,
    "from": true,
    "options": "Azul · Starlight · Roxo",
    "image": "./catalog/ipad.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "ipad-air-m4-128-gb-13-polegadas-wi-fi-70",
    "category": "iPad",
    "name": "iPad Air M4",
    "specs": "128 GB · 13 polegadas · Wi‑Fi",
    "price": 5403,
    "from": false,
    "options": "Cinza-espacial · Azul",
    "image": "./catalog/ipad.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "ipad-air-m4-128-gb-13-polegadas-wi-fi-cellular-71",
    "category": "iPad",
    "name": "iPad Air M4",
    "specs": "128 GB · 13 polegadas · Wi‑Fi + Cellular",
    "price": 6211,
    "from": false,
    "options": "Azul",
    "image": "./catalog/ipad.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "ipad-air-m4-256-gb-13-polegadas-wi-fi-72",
    "category": "iPad",
    "name": "iPad Air M4",
    "specs": "256 GB · 13 polegadas · Wi‑Fi",
    "price": 5959,
    "from": false,
    "options": "Cinza-espacial · Starlight · Azul",
    "image": "./catalog/ipad.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "ipad-pro-m5-256-gb-11-polegadas-wi-fi-73",
    "category": "iPad",
    "name": "iPad Pro M5",
    "specs": "256 GB · 11 polegadas · Wi‑Fi",
    "price": 6969,
    "from": false,
    "options": "Prateado · Space Black",
    "image": "./catalog/ipad.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "ipad-pro-m5-256-gb-13-polegadas-wi-fi-74",
    "category": "iPad",
    "name": "iPad Pro M5",
    "specs": "256 GB · 13 polegadas · Wi‑Fi",
    "price": 7827,
    "from": false,
    "options": "Space Black",
    "image": "./catalog/ipad.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "ipad-pro-m5-512-gb-13-polegadas-wi-fi-75",
    "category": "iPad",
    "name": "iPad Pro M5",
    "specs": "512 GB · 13 polegadas · Wi‑Fi",
    "price": 9241,
    "from": false,
    "options": "Space Black · Prateado",
    "image": "./catalog/ipad.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "ipad-pro-m5-1-tb-13-polegadas-wi-fi-76",
    "category": "iPad",
    "name": "iPad Pro M5",
    "specs": "1 TB · 13 polegadas · Wi‑Fi",
    "price": 10655,
    "from": false,
    "options": "Prateado",
    "image": "./catalog/ipad.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "ipad-pro-m5-256-gb-13-polegadas-wi-fi-cellular-77",
    "category": "iPad",
    "name": "iPad Pro M5",
    "specs": "256 GB · 13 polegadas · Wi‑Fi + Cellular",
    "price": 9745,
    "from": false,
    "options": "Space Black",
    "image": "./catalog/ipad.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "ipad-pro-m5-1-tb-13-polegadas-wi-fi-cellular-78",
    "category": "iPad",
    "name": "iPad Pro M5",
    "specs": "1 TB · 13 polegadas · Wi‑Fi + Cellular",
    "price": 11665,
    "from": false,
    "options": "Space Black",
    "image": "./catalog/ipad.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "ipad-pro-m5-nano-texture-1-tb-13-polegadas-wi-fi-cellular-79",
    "category": "iPad",
    "name": "iPad Pro M5 Nano-texture",
    "specs": "1 TB · 13 polegadas · Wi‑Fi + Cellular",
    "price": 11817,
    "from": false,
    "options": "Prateado",
    "image": "./catalog/ipad.webp",
    "details": "Vidro nano-texture",
    "badge": "M5"
  },
  {
    "id": "ipad-pro-m5-2-tb-13-polegadas-wi-fi-cellular-80",
    "category": "iPad",
    "name": "iPad Pro M5",
    "specs": "2 TB · 13 polegadas · Wi‑Fi + Cellular",
    "price": 12271,
    "from": false,
    "options": "Prateado",
    "image": "./catalog/ipad.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "macbook-air-m5-16-gb-512-gb-15-polegadas-seminovo-81",
    "category": "Mac",
    "name": "MacBook Air M5",
    "specs": "16 GB / 512 GB · 15 polegadas · seminovo",
    "price": 7624,
    "from": false,
    "options": "Midnight",
    "image": "./catalog/mac.webp",
    "details": "Caixa e cabo",
    "badge": "Seminovo"
  },
  {
    "id": "mac-mini-m4-16-gb-512-gb-82",
    "category": "Mac",
    "name": "Mac mini M4",
    "specs": "16 GB / 512 GB",
    "price": 5656,
    "from": false,
    "options": "Prateado",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "mac-mini-m4-24-gb-512-gb-83",
    "category": "Mac",
    "name": "Mac mini M4",
    "specs": "24 GB / 512 GB",
    "price": 8989,
    "from": false,
    "options": "Prateado",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "mac-mini-m6-16-gb-256-gb-84",
    "category": "Mac",
    "name": "Mac mini M6",
    "specs": "16 GB / 256 GB",
    "price": 7422,
    "from": false,
    "options": "Prateado",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "macbook-neo-8-gb-256-gb-13-polegadas-85",
    "category": "Mac",
    "name": "MacBook Neo",
    "specs": "8 GB / 256 GB · 13 polegadas",
    "price": 4585,
    "from": true,
    "options": "Amarelo · Rosa · Azul · Prateado",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "macbook-neo-8-gb-512-gb-13-polegadas-86",
    "category": "Mac",
    "name": "MacBook Neo",
    "specs": "8 GB / 512 GB · 13 polegadas",
    "price": 5301,
    "from": true,
    "options": "Prateado · Rosa · Azul · Amarelo",
    "image": "./catalog/mac.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "macbook-air-m5-16-gb-512-gb-13-polegadas-87",
    "category": "Mac",
    "name": "MacBook Air M5",
    "specs": "16 GB / 512 GB · 13 polegadas",
    "price": 8585,
    "from": false,
    "options": "Sky Blue · Midnight · Starlight · Prateado",
    "image": "./catalog/mac.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "macbook-air-m5-24-gb-1-tb-13-polegadas-88",
    "category": "Mac",
    "name": "MacBook Air M5",
    "specs": "24 GB / 1 TB · 13 polegadas",
    "price": 11361,
    "from": true,
    "options": "Prateado · Midnight",
    "image": "./catalog/mac.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "macbook-pro-m4-pro-24-gb-512-gb-14-polegadas-89",
    "category": "Mac",
    "name": "MacBook Pro M4 Pro",
    "specs": "24 GB / 512 GB · 14 polegadas",
    "price": 12270,
    "from": false,
    "options": "Prateado",
    "image": "./catalog/mac.webp",
    "details": "Chip M4 Pro",
    "badge": ""
  },
  {
    "id": "macbook-pro-m5-16-gb-1-tb-14-polegadas-90",
    "category": "Mac",
    "name": "MacBook Pro M5",
    "specs": "16 GB / 1 TB · 14 polegadas",
    "price": 11817,
    "from": true,
    "options": "Space Black · Prateado",
    "image": "./catalog/mac.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "macbook-pro-m5-pro-24-gb-1-tb-14-polegadas-91",
    "category": "Mac",
    "name": "MacBook Pro M5 Pro",
    "specs": "24 GB / 1 TB · 14 polegadas",
    "price": 15150,
    "from": false,
    "options": "Prateado",
    "image": "./catalog/mac.webp",
    "details": "Chip M5 Pro",
    "badge": "M5 Pro"
  },
  {
    "id": "macbook-pro-m5-pro-24-gb-1-tb-16-polegadas-92",
    "category": "Mac",
    "name": "MacBook Pro M5 Pro",
    "specs": "24 GB / 1 TB · 16 polegadas",
    "price": 17118,
    "from": true,
    "options": "Space Black · Prateado",
    "image": "./catalog/mac.webp",
    "details": "Chip M5 Pro",
    "badge": "M5 Pro"
  },
  {
    "id": "macbook-pro-m5-pro-48-gb-1-tb-16-polegadas-93",
    "category": "Mac",
    "name": "MacBook Pro M5 Pro",
    "specs": "48 GB / 1 TB · 16 polegadas",
    "price": 22370,
    "from": false,
    "options": "Prateado · Space Black",
    "image": "./catalog/mac.webp",
    "details": "Chip M5 Pro",
    "badge": "M5 Pro"
  },
  {
    "id": "macbook-pro-m5-max-36-gb-2-tb-14-polegadas-94",
    "category": "Mac",
    "name": "MacBook Pro M5 Max",
    "specs": "36 GB / 2 TB · 14 polegadas",
    "price": 23885,
    "from": false,
    "options": "Space Black",
    "image": "./catalog/mac.webp",
    "details": "Chip M5 Max",
    "badge": "M5 Max"
  },
  {
    "id": "macbook-pro-m5-max-36-gb-2-tb-16-polegadas-95",
    "category": "Mac",
    "name": "MacBook Pro M5 Max",
    "specs": "36 GB / 2 TB · 16 polegadas",
    "price": 26410,
    "from": false,
    "options": "Space Black · Prateado",
    "image": "./catalog/mac.webp",
    "details": "Chip M5 Max",
    "badge": "M5 Max"
  },
  {
    "id": "macbook-air-m4-16-gb-256-gb-15-polegadas-96",
    "category": "Mac",
    "name": "MacBook Air M4",
    "specs": "16 GB / 256 GB · 15 polegadas",
    "price": 8484,
    "from": false,
    "options": "Sky Blue",
    "image": "./catalog/mac.webp",
    "details": "Chip M4",
    "badge": ""
  },
  {
    "id": "macbook-air-m5-16-gb-256-gb-13-polegadas-97",
    "category": "Mac",
    "name": "MacBook Air M5",
    "specs": "16 GB / 256 GB · 13 polegadas",
    "price": 8635,
    "from": true,
    "options": "Midnight · Sky Blue · Prateado",
    "image": "./catalog/mac.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "macbook-air-m5-16-gb-1-tb-13-polegadas-98",
    "category": "Mac",
    "name": "MacBook Air M5",
    "specs": "16 GB / 1 TB · 13 polegadas",
    "price": 9645,
    "from": false,
    "options": "Sky Blue",
    "image": "./catalog/mac.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "macbook-air-m5-16-gb-512-gb-15-polegadas-99",
    "category": "Mac",
    "name": "MacBook Air M5",
    "specs": "16 GB / 512 GB · 15 polegadas",
    "price": 10352,
    "from": false,
    "options": "Starlight · Sky Blue",
    "image": "./catalog/mac.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "macbook-air-m5-16-gb-1-tb-15-polegadas-100",
    "category": "Mac",
    "name": "MacBook Air M5",
    "specs": "16 GB / 1 TB · 15 polegadas",
    "price": 11160,
    "from": false,
    "options": "Midnight",
    "image": "./catalog/mac.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "macbook-air-m5-24-gb-1-tb-15-polegadas-101",
    "category": "Mac",
    "name": "MacBook Air M5",
    "specs": "24 GB / 1 TB · 15 polegadas",
    "price": 12928,
    "from": false,
    "options": "Starlight · Sky Blue",
    "image": "./catalog/mac.webp",
    "details": "Chip M5",
    "badge": "M5"
  },
  {
    "id": "imac-m4-16-gb-256-gb-24-polegadas-8c-8c-102",
    "category": "Mac",
    "name": "iMac M4",
    "specs": "16 GB / 256 GB · 24 polegadas · 8C/8C",
    "price": 11514,
    "from": true,
    "options": "Prateado · Verde · Azul",
    "image": "./catalog/mac.webp",
    "details": "Duas portas",
    "badge": "M4"
  },
  {
    "id": "imac-m4-24-gb-512-gb-24-polegadas-10c-10c-103",
    "category": "Mac",
    "name": "iMac M4",
    "specs": "24 GB / 512 GB · 24 polegadas · 10C/10C",
    "price": 17978,
    "from": false,
    "options": "Prateado · Verde · Azul",
    "image": "./catalog/mac.webp",
    "details": "Quatro portas",
    "badge": "M4"
  },
  {
    "id": "mac-mini-m4-16-gb-256-gb-10c-10c-104",
    "category": "Mac",
    "name": "Mac mini M4",
    "specs": "16 GB / 256 GB · 10C/10C",
    "price": 5504,
    "from": false,
    "options": "Prateado",
    "image": "./catalog/mac.webp",
    "details": "Modelo A3238",
    "badge": "M4"
  },
  {
    "id": "mac-mini-m4-pro-24-gb-512-gb-12c-16c-105",
    "category": "Mac",
    "name": "Mac mini M4 Pro",
    "specs": "24 GB / 512 GB · 12C/16C",
    "price": 11362,
    "from": false,
    "options": "Prateado",
    "image": "./catalog/mac.webp",
    "details": "Modelo A3239",
    "badge": "M4 Pro"
  },
  {
    "id": "redmi-pad-2-4-gb-128-gb-106",
    "category": "Xiaomi",
    "name": "Redmi Pad 2",
    "specs": "4 GB / 128 GB",
    "price": 1313,
    "from": false,
    "options": "Cinza · Roxo",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-pad-2-8-gb-256-gb-107",
    "category": "Xiaomi",
    "name": "Redmi Pad 2",
    "specs": "8 GB / 256 GB",
    "price": 1463,
    "from": false,
    "options": "Cinza · Roxo · Verde",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-pad-2-4g-4-gb-128-gb-108",
    "category": "Xiaomi",
    "name": "Redmi Pad 2 4G",
    "specs": "4 GB / 128 GB",
    "price": 1384,
    "from": false,
    "options": "Cinza",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-a5-4-gb-128-gb-109",
    "category": "Xiaomi",
    "name": "Redmi A5",
    "specs": "4 GB / 128 GB",
    "price": 874,
    "from": false,
    "options": "Dourado",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-15-8-gb-256-gb-110",
    "category": "Xiaomi",
    "name": "Redmi 15",
    "specs": "8 GB / 256 GB",
    "price": 1261,
    "from": false,
    "options": "Preto · Cinza",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-15c-4-gb-128-gb-111",
    "category": "Xiaomi",
    "name": "Redmi 15C",
    "specs": "4 GB / 128 GB",
    "price": 909,
    "from": false,
    "options": "Preto · Verde",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-15c-nfc-4-gb-128-gb-112",
    "category": "Xiaomi",
    "name": "Redmi 15C NFC",
    "specs": "4 GB / 128 GB",
    "price": 929,
    "from": false,
    "options": "Preto · Verde",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-15c-4-gb-256-gb-113",
    "category": "Xiaomi",
    "name": "Redmi 15C",
    "specs": "4 GB / 256 GB",
    "price": 1020,
    "from": false,
    "options": "Verde · Preto",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-15c-8-gb-256-gb-114",
    "category": "Xiaomi",
    "name": "Redmi 15C",
    "specs": "8 GB / 256 GB",
    "price": 1091,
    "from": false,
    "options": "Preto · Azul · Verde",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-note-15-8-gb-256-gb-4g-115",
    "category": "Xiaomi",
    "name": "Redmi Note 15",
    "specs": "8 GB / 256 GB · 4G",
    "price": 1343,
    "from": false,
    "options": "Preto · Roxo",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-note-15-pro-8-gb-256-gb-4g-116",
    "category": "Xiaomi",
    "name": "Redmi Note 15 Pro",
    "specs": "8 GB / 256 GB · 4G",
    "price": 1687,
    "from": false,
    "options": "Azul · Cinza · Preto",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-note-15-pro-12-gb-512-gb-4g-117",
    "category": "Xiaomi",
    "name": "Redmi Note 15 Pro",
    "specs": "12 GB / 512 GB · 4G",
    "price": 1919,
    "from": false,
    "options": "Preto",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-note-15-pro-8-gb-256-gb-5g-118",
    "category": "Xiaomi",
    "name": "Redmi Note 15 Pro",
    "specs": "8 GB / 256 GB · 5G",
    "price": 1919,
    "from": false,
    "options": "Preto · Azul",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-note-15-pro-8-gb-512-gb-5g-119",
    "category": "Xiaomi",
    "name": "Redmi Note 15 Pro",
    "specs": "8 GB / 512 GB · 5G",
    "price": 2040,
    "from": false,
    "options": "Preto",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "redmi-note-15-pro-12-gb-512-gb-5g-120",
    "category": "Xiaomi",
    "name": "Redmi Note 15 Pro+",
    "specs": "12 GB / 512 GB · 5G",
    "price": 2505,
    "from": false,
    "options": "Preto",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "poco-c71-4-gb-128-gb-121",
    "category": "Xiaomi",
    "name": "POCO C71",
    "specs": "4 GB / 128 GB",
    "price": 869,
    "from": false,
    "options": "Preto · Dourado",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "poco-c81-pro-4-gb-128-gb-122",
    "category": "Xiaomi",
    "name": "POCO C81 Pro",
    "specs": "4 GB / 128 GB",
    "price": 889,
    "from": false,
    "options": "Dourado",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "poco-c85-6-gb-128-gb-123",
    "category": "Xiaomi",
    "name": "POCO C85",
    "specs": "6 GB / 128 GB",
    "price": 949,
    "from": false,
    "options": "Verde",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "poco-c85-8-gb-256-gb-124",
    "category": "Xiaomi",
    "name": "POCO C85",
    "specs": "8 GB / 256 GB",
    "price": 1091,
    "from": false,
    "options": "Preto · Roxo · Verde",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "poco-x8-pro-8-gb-256-gb-5g-125",
    "category": "Xiaomi",
    "name": "POCO X8 Pro",
    "specs": "8 GB / 256 GB · 5G",
    "price": 2303,
    "from": false,
    "options": "Preto · Verde · Branco",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "poco-x8-pro-12-gb-512-gb-5g-126",
    "category": "Xiaomi",
    "name": "POCO X8 Pro",
    "specs": "12 GB / 512 GB · 5G",
    "price": 2574,
    "from": true,
    "options": "Preto · Verde · Branco",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "poco-x8-pro-max-12-gb-256-gb-5g-127",
    "category": "Xiaomi",
    "name": "POCO X8 Pro Max",
    "specs": "12 GB / 256 GB · 5G",
    "price": 2969,
    "from": false,
    "options": "Branco · Azul",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "poco-x8-pro-max-12-gb-512-gb-5g-128",
    "category": "Xiaomi",
    "name": "POCO X8 Pro Max",
    "specs": "12 GB / 512 GB · 5G",
    "price": 3192,
    "from": true,
    "options": "Azul · Preto · Branco",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "xiaomi-17t-pro-12-gb-512-gb-5g-129",
    "category": "Xiaomi",
    "name": "Xiaomi 17T Pro",
    "specs": "12 GB / 512 GB · 5G",
    "price": 4323,
    "from": false,
    "options": "Roxo · Preto",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "poco-f8-ultra-16-gb-512-gb-5g-130",
    "category": "Xiaomi",
    "name": "POCO F8 Ultra",
    "specs": "16 GB / 512 GB · 5G",
    "price": 4585,
    "from": false,
    "options": "Preto",
    "image": "./catalog/xiaomi.webp",
    "details": "",
    "badge": ""
  },
  {
    "id": "iphone-13-128-gb-camera-com-mancha-131",
    "category": "iPhones seminovos",
    "name": "iPhone 13",
    "specs": "128 GB · câmera com mancha",
    "price": 1454,
    "from": false,
    "options": "Rosa",
    "image": "./products/iphone-13-pro.webp",
    "details": "30 dias de garantia",
    "badge": "Com detalhe"
  },
  {
    "id": "iphone-13-128-gb-bateria-100-132",
    "category": "iPhones seminovos",
    "name": "iPhone 13",
    "specs": "128 GB · bateria 100%",
    "price": 1848,
    "from": false,
    "options": "Branco · Rosa · Azul · Preto · Verde",
    "image": "./products/iphone-13-pro.webp",
    "details": "30 dias de garantia",
    "badge": "100% bateria"
  },
  {
    "id": "iphone-13-128-gb-versao-eua-133",
    "category": "iPhones seminovos",
    "name": "iPhone 13",
    "specs": "128 GB · versão EUA",
    "price": 1717,
    "from": true,
    "options": "Vermelho · Preto · Azul · Verde · Rosa · Branco",
    "image": "./products/iphone-13-pro.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-13-pro-128-gb-versao-eua-134",
    "category": "iPhones seminovos",
    "name": "iPhone 13 Pro",
    "specs": "128 GB · versão EUA",
    "price": 2333,
    "from": false,
    "options": "Azul · Preto",
    "image": "./products/iphone-13-pro.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-13-pro-256-gb-versao-eua-135",
    "category": "iPhones seminovos",
    "name": "iPhone 13 Pro",
    "specs": "256 GB · versão EUA",
    "price": 2525,
    "from": false,
    "options": "Azul · Preto",
    "image": "./products/iphone-13-pro.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-13-pro-max-128-gb-versao-eua-136",
    "category": "iPhones seminovos",
    "name": "iPhone 13 Pro Max",
    "specs": "128 GB · versão EUA",
    "price": 2606,
    "from": false,
    "options": "Verde · Preto · Azul · Dourado",
    "image": "./products/iphone-13-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-14-128-gb-bateria-100-137",
    "category": "iPhones seminovos",
    "name": "iPhone 14",
    "specs": "128 GB · bateria 100%",
    "price": 1838,
    "from": false,
    "options": "Preto · Roxo · Azul · Branco",
    "image": "./products/iphone-14-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "100% bateria"
  },
  {
    "id": "iphone-14-128-gb-versao-eua-138",
    "category": "iPhones seminovos",
    "name": "iPhone 14",
    "specs": "128 GB · versão EUA",
    "price": 1889,
    "from": true,
    "options": "Preto · Azul · Roxo · Branco",
    "image": "./products/iphone-14-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-14-pro-128-gb-bateria-100-139",
    "category": "iPhones seminovos",
    "name": "iPhone 14 Pro",
    "specs": "128 GB · bateria 100%",
    "price": 2675,
    "from": false,
    "options": "Preto · Branco · Dourado · Roxo",
    "image": "./products/iphone-14-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "100% bateria"
  },
  {
    "id": "iphone-14-pro-128-gb-versao-eua-140",
    "category": "iPhones seminovos",
    "name": "iPhone 14 Pro",
    "specs": "128 GB · versão EUA",
    "price": 2776,
    "from": false,
    "options": "Preto · Roxo",
    "image": "./products/iphone-14-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-14-pro-256-gb-versao-eua-141",
    "category": "iPhones seminovos",
    "name": "iPhone 14 Pro",
    "specs": "256 GB · versão EUA",
    "price": 2877,
    "from": false,
    "options": "Roxo · Branco · Dourado · Preto",
    "image": "./products/iphone-14-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-14-pro-max-128-gb-bateria-100-142",
    "category": "iPhones seminovos",
    "name": "iPhone 14 Pro Max",
    "specs": "128 GB · bateria 100%",
    "price": 2978,
    "from": false,
    "options": "Dourado · Roxo · Branco",
    "image": "./products/iphone-14-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "100% bateria"
  },
  {
    "id": "iphone-14-pro-max-128-gb-versao-eua-143",
    "category": "iPhones seminovos",
    "name": "iPhone 14 Pro Max",
    "specs": "128 GB · versão EUA",
    "price": 3020,
    "from": false,
    "options": "Preto · Roxo · Branco",
    "image": "./products/iphone-14-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-14-pro-max-256-gb-versao-eua-144",
    "category": "iPhones seminovos",
    "name": "iPhone 14 Pro Max",
    "specs": "256 GB · versão EUA",
    "price": 3281,
    "from": false,
    "options": "Roxo · Preto · Branco",
    "image": "./products/iphone-14-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-15-128-gb-bateria-100-145",
    "category": "iPhones seminovos",
    "name": "iPhone 15",
    "specs": "128 GB · bateria 100%",
    "price": 2545,
    "from": false,
    "options": "Preto · Azul",
    "image": "./products/iphone-15.webp",
    "details": "30 dias de garantia",
    "badge": "100% bateria"
  },
  {
    "id": "iphone-15-128-gb-versao-eua-146",
    "category": "iPhones seminovos",
    "name": "iPhone 15",
    "specs": "128 GB · versão EUA",
    "price": 2555,
    "from": false,
    "options": "Preto · Rosa · Azul · Verde",
    "image": "./products/iphone-15.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-15-plus-128-gb-versao-eua-147",
    "category": "iPhones seminovos",
    "name": "iPhone 15 Plus",
    "specs": "128 GB · versão EUA",
    "price": 2626,
    "from": true,
    "options": "Azul · Preto · Rosa",
    "image": "./products/iphone-15.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-15-pro-128-gb-148",
    "category": "iPhones seminovos",
    "name": "iPhone 15 Pro",
    "specs": "128 GB",
    "price": 3079,
    "from": false,
    "options": "Preto · Branco · Natural",
    "image": "./products/iphone-15.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-15-pro-128-gb-versao-eua-149",
    "category": "iPhones seminovos",
    "name": "iPhone 15 Pro",
    "specs": "128 GB · versão EUA",
    "price": 3180,
    "from": true,
    "options": "Azul · Preto · Branco · Natural",
    "image": "./products/iphone-15.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-15-pro-256-gb-versao-eua-150",
    "category": "iPhones seminovos",
    "name": "iPhone 15 Pro",
    "specs": "256 GB · versão EUA",
    "price": 3535,
    "from": true,
    "options": "Preto · Azul · Natural · Branco",
    "image": "./products/iphone-15.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-15-pro-max-256-gb-bateria-100-151",
    "category": "iPhones seminovos",
    "name": "iPhone 15 Pro Max",
    "specs": "256 GB · bateria 100%",
    "price": 3737,
    "from": false,
    "options": "Branco · Natural · Preto · Azul",
    "image": "./products/iphone-15.webp",
    "details": "30 dias de garantia",
    "badge": "100% bateria"
  },
  {
    "id": "iphone-15-pro-max-256-gb-versao-eua-152",
    "category": "iPhones seminovos",
    "name": "iPhone 15 Pro Max",
    "specs": "256 GB · versão EUA",
    "price": 3878,
    "from": false,
    "options": "Preto · Azul · Natural · Branco",
    "image": "./products/iphone-15.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-16-128-gb-versao-eua-153",
    "category": "iPhones seminovos",
    "name": "iPhone 16",
    "specs": "128 GB · versão EUA",
    "price": 3281,
    "from": true,
    "options": "Azul · Verde · Preto · Rosa · Branco",
    "image": "./products/iphone-16.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-16-256-gb-versao-eua-154",
    "category": "iPhones seminovos",
    "name": "iPhone 16",
    "specs": "256 GB · versão EUA",
    "price": 3584,
    "from": true,
    "options": "Verde · Azul · Preto",
    "image": "./products/iphone-16.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-16e-128-gb-versao-eua-155",
    "category": "iPhones seminovos",
    "name": "iPhone 16e",
    "specs": "128 GB · versão EUA",
    "price": 2525,
    "from": false,
    "options": "Preto · Branco",
    "image": "./products/iphone-16.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-16-plus-128-gb-versao-eua-156",
    "category": "iPhones seminovos",
    "name": "iPhone 16 Plus",
    "specs": "128 GB · versão EUA",
    "price": 3786,
    "from": false,
    "options": "Azul",
    "image": "./products/iphone-16.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-16-pro-128-gb-versao-eua-157",
    "category": "iPhones seminovos",
    "name": "iPhone 16 Pro",
    "specs": "128 GB · versão EUA",
    "price": 3838,
    "from": false,
    "options": "Branco · Desert · Natural · Preto",
    "image": "./products/iphone-16-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-16-pro-256-gb-versao-eua-158",
    "category": "iPhones seminovos",
    "name": "iPhone 16 Pro",
    "specs": "256 GB · versão EUA",
    "price": 4493,
    "from": false,
    "options": "Desert · Preto",
    "image": "./products/iphone-16-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-16-pro-max-256-gb-versao-eua-159",
    "category": "iPhones seminovos",
    "name": "iPhone 16 Pro Max",
    "specs": "256 GB · versão EUA",
    "price": 4594,
    "from": true,
    "options": "Preto · Desert · Natural · Branco",
    "image": "./products/iphone-16-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-16-pro-max-512-gb-versao-eua-160",
    "category": "iPhones seminovos",
    "name": "iPhone 16 Pro Max",
    "specs": "512 GB · versão EUA",
    "price": 5151,
    "from": false,
    "options": "Preto · Desert · Branco",
    "image": "./products/iphone-16-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-17-256-gb-versao-eua-161",
    "category": "iPhones seminovos",
    "name": "iPhone 17",
    "specs": "256 GB · versão EUA",
    "price": 4545,
    "from": true,
    "options": "Azul · Preto · Lavanda · Branco",
    "image": "./products/iphone-17.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-17-pro-256-gb-versao-eua-162",
    "category": "iPhones seminovos",
    "name": "iPhone 17 Pro",
    "specs": "256 GB · versão EUA",
    "price": 5959,
    "from": true,
    "options": "Laranja · Azul · Prateado",
    "image": "./products/iphone-17-pro.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-17-pro-max-256-gb-versao-eua-163",
    "category": "iPhones seminovos",
    "name": "iPhone 17 Pro Max",
    "specs": "256 GB · versão EUA",
    "price": 6358,
    "from": true,
    "options": "Laranja · Azul · Prateado",
    "image": "./products/iphone-17-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-17-pro-max-512-gb-versao-eua-164",
    "category": "iPhones seminovos",
    "name": "iPhone 17 Pro Max",
    "specs": "512 GB · versão EUA",
    "price": 7272,
    "from": true,
    "options": "Laranja · Azul · Branco",
    "image": "./products/iphone-17-pro-max.webp",
    "details": "30 dias de garantia",
    "badge": "85–100% bateria"
  },
  {
    "id": "iphone-15-128-gb-chip-fisico-esim-165",
    "category": "iPhones lacrados",
    "name": "iPhone 15",
    "specs": "128 GB · chip físico + eSIM",
    "price": 3737,
    "from": true,
    "options": "Azul · Preto",
    "image": "./products/iphone-15.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-15-256-gb-chip-fisico-esim-166",
    "category": "iPhones lacrados",
    "name": "iPhone 15",
    "specs": "256 GB · chip físico + eSIM",
    "price": 4393,
    "from": false,
    "options": "Preto · Azul",
    "image": "./products/iphone-15.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-15-plus-256-gb-167",
    "category": "iPhones lacrados",
    "name": "iPhone 15 Plus",
    "specs": "256 GB",
    "price": 4747,
    "from": false,
    "options": "Rosa",
    "image": "./products/iphone-15.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-16-128-gb-chip-fisico-esim-168",
    "category": "iPhones lacrados",
    "name": "iPhone 16",
    "specs": "128 GB · chip físico + eSIM",
    "price": 4191,
    "from": true,
    "options": "Rosa · Branco · Preto · Verde · Azul",
    "image": "./products/iphone-16.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-16-pro-max-256-gb-esim-169",
    "category": "iPhones lacrados",
    "name": "iPhone 16 Pro Max",
    "specs": "256 GB · eSIM",
    "price": 6464,
    "from": false,
    "options": "Desert",
    "image": "./products/iphone-16-pro-max.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-17e-256-gb-chip-fisico-esim-170",
    "category": "iPhones lacrados",
    "name": "iPhone 17e",
    "specs": "256 GB · chip físico + eSIM",
    "price": 3686,
    "from": true,
    "options": "Preto · Branco · Rosa",
    "image": "./products/iphone-17e.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-17-air-256-gb-esim-171",
    "category": "iPhones lacrados",
    "name": "iPhone 17 Air",
    "specs": "256 GB · eSIM",
    "price": 5050,
    "from": true,
    "options": "Branco · Preto · Dourado · Azul",
    "image": "./products/iphone-17-air.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-17-pro-256-gb-esim-172",
    "category": "iPhones lacrados",
    "name": "iPhone 17 Pro",
    "specs": "256 GB · eSIM",
    "price": 6716,
    "from": true,
    "options": "Laranja · Branco · Azul",
    "image": "./products/iphone-17-pro.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-17-pro-512-gb-esim-173",
    "category": "iPhones lacrados",
    "name": "iPhone 17 Pro",
    "specs": "512 GB · eSIM",
    "price": 8029,
    "from": true,
    "options": "Laranja · Branco Anatel · Azul",
    "image": "./products/iphone-17-pro.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-17-pro-max-256-gb-esim-174",
    "category": "iPhones lacrados",
    "name": "iPhone 17 Pro Max",
    "specs": "256 GB · eSIM",
    "price": 6716,
    "from": false,
    "options": "Laranja",
    "image": "./products/iphone-17-pro-max.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-17-pro-max-512-gb-esim-175",
    "category": "iPhones lacrados",
    "name": "iPhone 17 Pro Max",
    "specs": "512 GB · eSIM",
    "price": 8433,
    "from": false,
    "options": "Laranja · Branco · Azul",
    "image": "./products/iphone-17-pro-max.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-17-pro-max-512-gb-anatel-176",
    "category": "iPhones lacrados",
    "name": "iPhone 17 Pro Max",
    "specs": "512 GB · Anatel",
    "price": 8635,
    "from": false,
    "options": "Laranja",
    "image": "./products/iphone-17-pro-max.webp",
    "details": "Novo e lacrado",
    "badge": "Anatel"
  },
  {
    "id": "iphone-18-pro-256-gb-esim-177",
    "category": "iPhones lacrados",
    "name": "iPhone 18 Pro",
    "specs": "256 GB · eSIM",
    "price": 7928,
    "from": false,
    "options": "Preto · Azul",
    "image": "./products/iphone-18-pro.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-18-pro-max-256-gb-esim-178",
    "category": "iPhones lacrados",
    "name": "iPhone 18 Pro Max",
    "specs": "256 GB · eSIM",
    "price": 9039,
    "from": true,
    "options": "Bordô · Azul · Branco · Preto",
    "image": "./products/iphone-18-pro-max.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-18-pro-max-512-gb-esim-179",
    "category": "iPhones lacrados",
    "name": "iPhone 18 Pro Max",
    "specs": "512 GB · eSIM",
    "price": 10352,
    "from": false,
    "options": "Preto · Azul",
    "image": "./products/iphone-18-pro-max.webp",
    "details": "Novo e lacrado",
    "badge": "Lacrado"
  },
  {
    "id": "iphone-13-pro-128-gb-180",
    "category": "iPhones lacrados",
    "name": "iPhone 13 Pro",
    "specs": "128 GB",
    "price": 3030,
    "from": false,
    "options": "Preto",
    "image": "./products/iphone-13-pro.webp",
    "details": "CPO · consulte a garantia disponível",
    "badge": "CPO"
  },
  {
    "id": "iphone-16-128-gb-esim-181",
    "category": "iPhones lacrados",
    "name": "iPhone 16",
    "specs": "128 GB · eSIM",
    "price": 4191,
    "from": false,
    "options": "Rosa",
    "image": "./products/iphone-16.webp",
    "details": "CPO · consulte a garantia disponível",
    "badge": "CPO"
  },
  {
    "id": "iphone-16-256-gb-182",
    "category": "iPhones lacrados",
    "name": "iPhone 16",
    "specs": "256 GB",
    "price": 4494,
    "from": false,
    "options": "Branco",
    "image": "./products/iphone-16.webp",
    "details": "CPO · consulte a garantia disponível",
    "badge": "CPO"
  },
  {
    "id": "iphone-16-pro-128-gb-esim-183",
    "category": "iPhones lacrados",
    "name": "iPhone 16 Pro",
    "specs": "128 GB · eSIM",
    "price": 4949,
    "from": false,
    "options": "Natural",
    "image": "./products/iphone-16-pro-max.webp",
    "details": "CPO · consulte a garantia disponível",
    "badge": "CPO"
  }
];


